### ISSUE TITLE
Rate Card - autoselect based on Contract

### ISSUE THREAD

**Issue by craig5smiths** [MyNationEarth/NetWorks#1]
Phil,
I am not getting the auto selection of rate card when I put a new project in and have already selected the Contract.

**Comment by JupiterJones** [comment]
The first job created in a project will need to have a rate card selected. Any subsequent jobs created in a project will default to the same rate card as the first job.

**Comment by craig5smiths** [comment]
I noticed that one. Thanks.

 
Regards

 
Craig Smith

Director

 

1/12 Eddie Rd

Minchinbury NSW 2770

0412533141     

 
*******************************************************************************

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. 

 
5Smiths, PO Box 169, Maroubra, NSW, Australia, www.5smiths.com.au <http://www.5smiths.com.au/> 

*******************************************************************************

**Comment by craig5smiths** [comment]
Hey mate,

 
Have you defaulted this to always select the contract from the new Project screen? It appears to be the case now for some projects I am entering.

 
Regards

 
Craig Smith

Director

 

1/12 Eddie Rd

Minchinbury NSW 2770

0412533141     

 
*******************************************************************************

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. 

 
5Smiths, PO Box 169, Maroubra, NSW, Australia, www.5smiths.com.au <http://www.5smiths.com.au/> 

*******************************************************************************

**Comment by JupiterJones** [comment]
Rate card’s aren’t specifically tied to a contract. This way, if for any reason, you need to do something from another rate card for a job, there is the option to do that.

The way it works is: First job created, select the rate card, and every other job after that will default to the same rate card, but allow you to select another if need be.

**Comment by craig5smiths** [comment]
Cool, no stress.

 
Regards

 
Craig Smith

Director

 

1/12 Eddie Rd

Minchinbury NSW 2770

0412533141     

 
*******************************************************************************

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. 

 
5Smiths, PO Box 169, Maroubra, NSW, Australia, www.5smiths.com.au <http://www.5smiths.com.au/> 

*******************************************************************************
